"""add_badges_enhancements_and_course_badges

Revision ID: b08dc4b458b6
Revises: 431fd67f82d2
Create Date: 2026-03-12 13:04:39.052861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b08dc4b458b6'
down_revision: Union[str, Sequence[str], None] = '431fd67f82d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('main_color', sa.String(length=20), server_default='#3b82f6', nullable=False))
    op.add_column('badges', sa.Column('secondary_color', sa.String(length=20), server_default='#1e40af', nullable=False))
    
    # Create course_badges table
    op.create_table('course_badges',
        sa.Column('course_id', sa.CHAR(length=36), nullable=False),
        sa.Column('badge_id', sa.CHAR(length=36), nullable=False),
        sa.Column('progress_percentage', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('100.00'), nullable=False),
        sa.Column('id', sa.CHAR(length=36), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('course_id', 'badge_id', name='uq_course_badges_course_badge')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_badges')
    op.drop_column('badges', 'secondary_color')
    op.drop_column('badges', 'main_color')
    # ### end Alembic commands ###